# Generated by Django 3.1.4 on 2021-01-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_auto_20210123_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
