# Generated by Django 3.1.6 on 2021-04-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('tools', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('img_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
