# Generated by Django 3.1.6 on 2021-04-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Contact',
        ),
    ]
