# Generated by Django 3.1.6 on 2021-04-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
